# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import times_pb2 as times__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in times_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TimesStub(object):
    """Service gRPC équivalent à ton API REST Times
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetScheduleByDate = channel.unary_unary(
                '/times.Times/GetScheduleByDate',
                request_serializer=times__pb2.DateRequest.SerializeToString,
                response_deserializer=times__pb2.TimesReply.FromString,
                _registered_method=True)
        self.AddSchedule = channel.unary_unary(
                '/times.Times/AddSchedule',
                request_serializer=times__pb2.ScheduleDay.SerializeToString,
                response_deserializer=times__pb2.TimesReply.FromString,
                _registered_method=True)
        self.DeleteSchedule = channel.unary_unary(
                '/times.Times/DeleteSchedule',
                request_serializer=times__pb2.DateRequest.SerializeToString,
                response_deserializer=times__pb2.TimesReply.FromString,
                _registered_method=True)


class TimesServicer(object):
    """Service gRPC équivalent à ton API REST Times
    """

    def GetScheduleByDate(self, request, context):
        """GET /schedule/<date>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSchedule(self, request, context):
        """POST /schedule
        on envoie directement un ScheduleDay (date + movies)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSchedule(self, request, context):
        """DELETE /schedule/<date>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetScheduleByDate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScheduleByDate,
                    request_deserializer=times__pb2.DateRequest.FromString,
                    response_serializer=times__pb2.TimesReply.SerializeToString,
            ),
            'AddSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSchedule,
                    request_deserializer=times__pb2.ScheduleDay.FromString,
                    response_serializer=times__pb2.TimesReply.SerializeToString,
            ),
            'DeleteSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSchedule,
                    request_deserializer=times__pb2.DateRequest.FromString,
                    response_serializer=times__pb2.TimesReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'times.Times', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('times.Times', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Times(object):
    """Service gRPC équivalent à ton API REST Times
    """

    @staticmethod
    def GetScheduleByDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/times.Times/GetScheduleByDate',
            times__pb2.DateRequest.SerializeToString,
            times__pb2.TimesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/times.Times/AddSchedule',
            times__pb2.ScheduleDay.SerializeToString,
            times__pb2.TimesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/times.Times/DeleteSchedule',
            times__pb2.DateRequest.SerializeToString,
            times__pb2.TimesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
