# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: times.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'times.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btimes.proto\x12\x05times\"+\n\x0bScheduleDay\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\x1b\n\x0b\x44\x61teRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"M\n\nTimesReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x1f\n\x03\x64\x61y\x18\x03 \x01(\x0b\x32\x12.times.ScheduleDay2\xb2\x01\n\x05Times\x12:\n\x11GetScheduleByDate\x12\x12.times.DateRequest\x1a\x11.times.TimesReply\x12\x34\n\x0b\x41\x64\x64Schedule\x12\x12.times.ScheduleDay\x1a\x11.times.TimesReply\x12\x37\n\x0e\x44\x65leteSchedule\x12\x12.times.DateRequest\x1a\x11.times.TimesReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'times_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCHEDULEDAY']._serialized_start=22
  _globals['_SCHEDULEDAY']._serialized_end=65
  _globals['_DATEREQUEST']._serialized_start=67
  _globals['_DATEREQUEST']._serialized_end=94
  _globals['_TIMESREPLY']._serialized_start=96
  _globals['_TIMESREPLY']._serialized_end=173
  _globals['_TIMES']._serialized_start=176
  _globals['_TIMES']._serialized_end=354
# @@protoc_insertion_point(module_scope)
